### ISSUE TITLE
Crash in `DaedalusVm::print_stack_trace`

### ISSUE THREAD

**Issue by Try** [GothicKit/ZenKit#100]
Run into this issue when testing on Archolos.

Offended part of code:
```c++
if (_m_instance != nullptr) {
  auto instance_symbol = find_symbol_by_instance(_m_instance); // instance_symbol might be null here
  ZKLOGE("DaedalusVm", "<__THIS__> = %s (%u)", instance_symbol->name().c_str(), _m_instance->symbol_index()); // crash
  } else {
  ZKLOGE("DaedalusVm", "<__THIS__> = NULL");
  }
}
```

While at it `_m_symbol_index->_m_symbol_index == 4294967295`. I'm not sure what exactly is that, probably pinned memory.

**Comment by lmichaelis** [comment]
Thanks for the report. I've added an initial fix in 4adcbcb0, please report back whether it works.

**Comment by Try** [comment]
I've pulled latest commit locally.
Now game cannot start, resulting into error message:
`loading error: failed parsing resource of type ReadArchive.Binsafe [context: invalid format]`

Reproducible in vanilla night of the raven, with `vesion==zenkit::GameVersion::GOTHIC_2`.

Offended part of source:
```c++
	template <ArchiveEntryType tp>
	std::uint16_t ReadArchiveBinsafe::ensure_entry_meta() {
		auto type = static_cast<ArchiveEntryType>(read->read_ubyte());

		if (type != ArchiveEntryType::HASH) {  // <-- zenkit::ArchiveEntryType::STRING
			throw ParserError {"ReadArchive.Binsafe", "invalid format"};
		}
```
---
Gothic1 also broken, spamming:
```
[zenkit] Object not fully loaded: À
[zenkit] Unknown object type: À
```

My previous commit, before git-pool: `037db91`

**Comment by Try** [comment]
both issues are fixed now
